name: s3 deployment connect-websocket branch

on:
  workflow_dispatch: #not sure about this part
  push:
    # the branch(es) we want this to run on
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # required to use OIDC authentication
      contents: read # required to checkout the code from the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}}
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: ap-southeast-2 # use your region here.

      - name: npm install
        run: npm i

      - name: copy files to s3
        run: aws s3 sync ./client s3://${{secrets.AWS_S3_BUCKET}}

      - name: Invalidate cache
        run: |
          aws cloudfront  create-invalidation --distribution-id ${{secrets.AWS_CLOUDFRONT_DIST}} --paths "/*"
